services:
  blazorapp1:
    image: blazorapp1
    build:
      context: .
      dockerfile: BlazorApp1/BlazorApp1/Dockerfile

  blazorapp1.client:
    image: blazorapp1.client
    build:
      context: .
      dockerfile: BlazorApp1/BlazorApp1.Client/Dockerfile

  ruisantos.autofill.web:
    image: ruisantos.autofill.web
    build:
      context: .
      dockerfile: RuiSantos.AutoFill.Web/RuiSantos.AutoFill.Web/Dockerfile

  ruisantos.autofill.web.client:
    image: ruisantos.autofill.web.client
    build:
      context: .
      dockerfile: RuiSantos.AutoFill.Web/RuiSantos.AutoFill.Web.Client/Dockerfile

  ruisantos.autofill.web-1:
    image: ruisantos.autofill.web-1
    build:
      context: .
      dockerfile: RuiSantos.AutoFill.Web/Dockerfile
