services:
  autofill_web:
    image: ruisantos.autofill.web
    build:
      context: .
      dockerfile: RuiSantos.AutoFill.Web/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - MONGO_SERVER_HOST=autofill_db
      - MONGO_SERVER_PORT=27017
      - MONGO_DATABASE=admin
      - MONGO_USER=admin
      - MONGO_PASSWORD=securepassword
    volumes:
      - data_protection_keys:/app/keys
    depends_on:
      - autofill_db
    networks:
      - autofill-network
  
  autofill_db:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=securepassword
    volumes:
      - mongodb_data:/data/db
    networks:
      - autofill-network

networks:
  autofill-network:

volumes:
  mongodb_data:
  data_protection_keys: